-- Create network_logos table to store network branding
CREATE TABLE IF NOT EXISTS network_logos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  network_name VARCHAR(50) UNIQUE NOT NULL,
  logo_data TEXT NOT NULL, -- Base64 encoded image or SVG
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add RLS policy
ALTER TABLE network_logos ENABLE ROW LEVEL SECURITY;

-- Public read access for network logos
CREATE POLICY "Public can read network logos" ON network_logos
  FOR SELECT USING (true);

-- Insert default network logos
INSERT INTO network_logos (network_name, logo_data) VALUES
('MTN', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgMzAwIj48cmVjdCBmaWxsPSIjRkZENzAwIiB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIvPjxyZWN0IHg9IjEwMCIgeT0iNzUiIHdpZHRoPSIyMDAiIGhlaWdodD0iMTUwIiByeD0iMjAiIGZpbGw9IiMwMDAiIG9wYWNpdHk9IjAuOCIvPjx0ZXh0IHg9IjIwMCIgeT0iMTcwIiBmb250LXNpemU9IjgwIiBmb250LXdlaWdodD0iOTAwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSIjRkZGIiBmb250LWZhbWlseT0iQXJpYWwiPk1UTjwvdGV4dD48L3N2Zz4='),
('Telecel', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgMzAwIj48cmVjdCBmaWxsPSIjRTYwMDAwIiB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIvPjxjaXJjbGUgY3g9IjIwMCIgY3k9IjEzMCIgcj0iNjAiIGZpbGw9IiNGRkYiLz48dGV4dCB4PSIyMDAiIHk9IjE0NSIgZm9udC1zaXplPSI2MCIgZm9udC13ZWlnaHQ9IjkwMCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iI0U2MDAwMCIgZm9udC1mYW1pbHk9IkFyaWFsIj50PC90ZXh0Pjx0ZXh0IHg9IjIwMCIgeT0iMjIwIiBmb250LXNpemU9IjQ4IiBmb250LXdlaWdodD0iYm9sZCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iI0ZGRiIgZm9udC1mYW1pbHk9IkFyaWFsIj50ZWxlY2VsPC90ZXh0Pjwvc3ZnPg=='),
('Vodafone', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgMzAwIj48cmVjdCBmaWxsPSIjRTYwMDAwIiB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIvPjx0ZXh0IHg9IjIwMCIgeT0iMTcwIiBmb250LXNpemU9IjcyIiBmb250LXdlaWdodD0iOTAwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSIjRkZGIiBmb250LWZhbWlseT0iQXJpYWwiPlZvZGFmb25lPC90ZXh0Pjwvc3ZnPg=='),
('AT', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgMzAwIj48cmVjdCBmaWxsPSIjMUIzRTdCIiB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIvPjxwYXRoIGQ9Ik0gMTUwIDEwMCBMIDE4MCAxNTAgTCAxNTAgMTUwIFoiIGZpbGw9IiNFNzRDM0MiLz48cGF0aCBkPSJNIDI1MCAxMDAgTCAyODAgMTUwIEwgMjUwIDE1MCBaIiBmaWxsPSIjRTc0QzNDIi8+PHBhdGggZD0iTSAyMDAgMTgwIFEgMTgwIDIyMCAyMDAgMjQwIFEgMjIwIDIyMCAyMDAgMTgwIiBmaWxsPSIjRTc0QzNDIi8+PHRleHQgeD0iMjAwIiB5PSIyNzAiIGZvbnQtc2l6ZT0iNDAiIGZvbnQtd2VpZ2h0PSI5MDAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiNFNzRDM0MiIGZvbnQtZmFtaWx5PSJBcmlhbCI+YXQ8L3RleHQ+PC9zdmc+'),
('Airtel', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgMzAwIj48cmVjdCBmaWxsPSIjRTEwNTBFIiB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIvPjx0ZXh0IHg9IjIwMCIgeT0iMTcwIiBmb250LXNpemU9IjcyIiBmb250LXdlaWdodD0iOTAwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSIjRkZGIiBmb250LWZhbWlseT0iQXJpYWwiPkFpcnRlbDwvdGV4dD48L3N2Zz4='),
('iShare', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgMzAwIj48cmVjdCBmaWxsPSIjRkY2NjAwIiB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIvPjx0ZXh0IHg9IjIwMCIgeT0iMTcwIiBmb250LXNpemU9IjcyIiBmb250LXdlaWdodD0iOTAwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSIjRkZGIiBmb250LWZhbWlseT0iQXJpYWwiPmlTaGFyZTwvdGV4dD48L3N2Zz4=')
ON CONFLICT (network_name) DO NOTHING;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_network_logos_name ON network_logos(network_name);
